### ISSUE TITLE
[BUG] Swiper don't see Container

### ISSUE THREAD

**Issue by GeorgeHop** [GeorgeHop/react-native-screens-swiper#2]
Hi @dorkyboi, @GeorgeHop ,
First of all thank you for creating this really simple screen swiper library.
I installed it in my app and simple copy your example code in my app and facing this issue,
_Error: Unable to resolve module ./Container from \node_modules\react-native-screens-swiper\components\Swiper.js:_
Could you please guide me that how I resolve this issue?

Thank you

![image](https://user-images.githubusercontent.com/72445787/135627665-b684b2de-0219-405d-98fd-2c163921e6c0.png)

_Originally posted by @ansar-imam in https://github.com/GeorgeHop/react-native-screens-swiper/issues/1#issuecomment-932227429_

**Comment by GeorgeHop** [comment]
Please provide version of swiper which you use :-)

**Comment by dorkyboi** [comment]
Hey @ansar-imam
We have tested importing on a brand new project created with `expo init` and it worked as expected.
Could you elaborate more on how you created your project or how it is set up? Perhaps there's something wrong with bundler.

**Comment by sami-sy** [comment]
Same issue for me, I'm using cli 0.64.0 and swiper version 1.2.4

**Comment by GeorgeHop** [comment]
Hello @sami-sym, sorry for delaying. 
Can you describe please your environment setup ? How we said above it can be some problems with the bundler, but for some reasons it can be some other stuff. Provide more info please !

**Comment by Hubi1234** [comment]
I had the same problem, but the issue could be resolved by adjusting the metro.config.js file. Your resolver needs to include "jsx" otherwise the Container.jsx file can not be resolved.

something like that: 
`module.exports = {
  resolver: {
    sourceExts: ["jsx", "js", "ts", "tsx"]
  }
};`
